# Generated by Django 3.2 on 2022-11-28 12:00

import apps.products.models
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Peso')),
            ],
            options={
                'verbose_name': 'Jaba',
                'verbose_name_plural': 'Jabas',
            },
        ),
        migrations.CreateModel(
            name='Fruits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Frutas',
                'verbose_name_plural': 'Frutas',
            },
        ),
        migrations.CreateModel(
            name='HistoricalBoxes',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Peso')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Jaba',
                'verbose_name_plural': 'historical Jabas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFruits',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Frutas',
                'verbose_name_plural': 'historical Frutas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPackingProduct',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('entry_date', models.DateField(verbose_name='Fecha de ingreso')),
                ('production_date', models.DateField(verbose_name='Fecha de producción')),
                ('expiration_date', models.DateField(verbose_name='Fecha de vencimiento')),
                ('docs', models.TextField(blank=True, max_length=100, null=True, verbose_name='Documentos')),
                ('type', models.CharField(choices=[('Bolsas', 'Bolsas'), ('Cajas', 'Cajas')], default='Bolsas', max_length=100, verbose_name='Tipo')),
                ('lot', models.CharField(max_length=50, verbose_name='Lote')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Envase/Embalaje',
                'verbose_name_plural': 'historical Envases/Embalajes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPallets',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Peso')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Pallet',
                'verbose_name_plural': 'historical Pallets',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Pallets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Peso')),
            ],
            options={
                'verbose_name': 'Pallet',
                'verbose_name_plural': 'Pallets',
            },
        ),
        migrations.CreateModel(
            name='PackingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(verbose_name='Fecha de ingreso')),
                ('production_date', models.DateField(verbose_name='Fecha de producción')),
                ('expiration_date', models.DateField(verbose_name='Fecha de vencimiento')),
                ('docs', models.FileField(blank=True, null=True, upload_to=apps.products.models.custom_doc_file_path, verbose_name='Documentos')),
                ('type', models.CharField(choices=[('Bolsas', 'Bolsas'), ('Cajas', 'Cajas')], default='Bolsas', max_length=100, verbose_name='Tipo')),
                ('lot', models.CharField(max_length=50, verbose_name='Lote')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='business_partners.providerpacking', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Envase/Embalaje',
                'verbose_name_plural': 'Envases/Embalajes',
                'ordering': ['-entry_date'],
            },
        ),
    ]
