# Generated by Django 3.2 on 2022-11-17 20:44

import apps.products.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_partners', '0002_client_providerpacking'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(verbose_name='Fecha de ingreso')),
                ('production_date', models.DateField(verbose_name='Fecha de producción')),
                ('expiration_date', models.DateField(verbose_name='Fecha de vencimiento')),
                ('docs', models.FileField(blank=True, null=True, upload_to=apps.products.models.custom_doc_file_path, verbose_name='Documentos')),
                ('quantity', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('type', models.CharField(choices=[('Bolsas', 'Bolsas'), ('Cajas', 'Cajas')], default='Bolsas', max_length=100, verbose_name='Tipo')),
                ('lot', models.CharField(max_length=50, verbose_name='Lote')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_partners.providerpacking', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-entry_date'],
            },
        ),
    ]
