# Generated by Django 3.2 on 2022-12-04 19:14

import apps.products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruits',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=apps.products.models.custom_doc_file),
        ),
        migrations.AddField(
            model_name='historicalfruits',
            name='thumbnail',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
