# Generated by Django 3.2 on 2022-11-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_packingproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Peso')),
            ],
            options={
                'verbose_name': 'Jaba',
                'verbose_name_plural': 'Jabas',
            },
        ),
        migrations.CreateModel(
            name='Pallets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Peso')),
            ],
            options={
                'verbose_name': 'Pallet',
                'verbose_name_plural': 'Pallets',
            },
        ),
    ]
