# Generated by Django 3.2 on 2022-11-17 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_boxes_pallets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fruits',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='fruits',
            name='to',
        ),
    ]
