# Generated by Django 3.2 on 2022-11-17 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('raw_material', '0003_rename_informacion_ilot'),
        ('products', '0005_auto_20221117_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessPineapple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha de Proceso')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('juice', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=4, null=True, verbose_name='Jugo')),
                ('discard', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=4, null=True, verbose_name='Descarte')),
                ('start_washed', models.TimeField(blank=True, null=True, verbose_name='Inicio de lavado')),
                ('start_bare', models.TimeField(blank=True, null=True, verbose_name='Inicio de pelado')),
                ('start_chopped', models.TimeField(blank=True, null=True, verbose_name='Inicio de picado')),
                ('start_loaded', models.TimeField(blank=True, null=True, verbose_name='Inicio de cargado')),
                ('start_cleaning', models.TimeField(blank=True, null=True, verbose_name='Inicio de limpieza')),
                ('finish_washed', models.TimeField(blank=True, null=True, verbose_name='Fin de lavado')),
                ('finish_bare', models.TimeField(blank=True, null=True, verbose_name='Fin de pelado')),
                ('finish_chopped', models.TimeField(blank=True, null=True, verbose_name='Fin de picado')),
                ('finish_loaded', models.TimeField(blank=True, null=True, verbose_name='Fin de cargado')),
                ('finish_cleaning', models.TimeField(blank=True, null=True, verbose_name='Fin de limpieza ')),
                ('people', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Personas')),
                ('kg_unpeeled', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=4, null=True, verbose_name='Kg sin pelar')),
                ('cars', models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='Cantidad de Coches')),
                ('status', models.BooleanField(default=False, verbose_name='Cerrado/Abierto')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_pineapple', to='raw_material.lot', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Proceso de Piña',
                'verbose_name_plural': 'Procesos de Piña',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Peel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Peso')),
                ('quantity', models.PositiveSmallIntegerField(default=0, verbose_name='Cantidad')),
                ('pallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.pallets', verbose_name='Pallet')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peel', to='production.processpineapple', verbose_name='Proceso')),
            ],
            options={
                'verbose_name': 'Proceso de Piña - Cáscara',
                'verbose_name_plural': 'Proceso de Piña - Cáscara',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Crown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(verbose_name='Peso')),
                ('pallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.pallets', verbose_name='Pallet')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crown', to='production.processpineapple', verbose_name='Proceso')),
            ],
            options={
                'verbose_name': 'Proceso de Piña - Corona',
                'verbose_name_plural': 'Proceso de Piña - Corona',
                'ordering': ('id',),
            },
        ),
    ]
