# Generated by Django 3.2 on 2022-11-17 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crown',
            options={'ordering': ('id',), 'verbose_name': 'Registro de Piña - Corona', 'verbose_name_plural': 'Registro de Piña - Corona'},
        ),
        migrations.AlterModelOptions(
            name='peel',
            options={'ordering': ('id',), 'verbose_name': 'Registro de Piña - Cáscara', 'verbose_name_plural': 'Registro de Piña - Cáscara'},
        ),
    ]
