// Alerts
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';


/*Products*/
export const GET_FRUITS_SUCCESS = 'GET_FRUITS_SUCCESS';
export const GET_FRUITS_FAIL = 'GET_FRUITS_FAIL';


export const GET_PALLETS_SUCCESS = 'GET_PALLETS_SUCCESS';
export const GET_PALLETS_FAIL = 'GET_PALLETS_FAIL';


/*MANAGEMENT*/
export const GET_KARDEX_SUCCESS = 'GET_KARDEX_SUCCESS';
export const GET_KARDEX_FAIL = 'GET_KARDEX_FAIL';
export const ADD_KARDEX_SUCCESS = 'ADD_KARDEX_SUCCESS';
export const ADD_KARDEX_FAIL = 'ADD_KARDEX_FAIL';


export const GET_MOTIONS_SUCCESS = 'GET_MOTIONS_SUCCESS';
export const GET_MOTIONS_FAIL = 'GET_MOTIONS_FAIL';
export const DELETE_MOTION_SUCCESS = 'DELETE_MOTION_SUCCESS';
export const DELETE_MOTION_FAIL = 'DELETE_MOTION_FAIL';
export const ADD_MOTION_SUCCESS = 'ADD_MOTION_SUCCESS';
export const ADD_MOTION_FAIL = 'ADD_MOTION_FAIL';

export const GET_PAYMENTS_SUCCESS = 'GET_PAYMENTS_SUCCESS'
export const GET_PAYMENTS_FAIL = 'GET_PAYMENTS_FAIL'
export const ADD_PAYMENTS_SUCCESS = 'ADD_PAYMENTS_SUCCESS'
export const ADD_PAYMENTS_FAIL = 'ADD_PAYMENTS_FAIL'
export const UPDATE_PAYMENTS_SUCCESS = 'UPDATE_PAYMENTS_SUCCESS'
export const UPDATE_PAYMENTS_FAIL = 'UPDATE_PAYMENTS_FAIL'
export const DELETE_PAYMENTS_SUCCESS = 'DELETE_PAYMENTS_SUCCESS'
export const DELETE_PAYMENTS_FAIL = 'DELETE_PAYMENTS_FAIL'


/*BUSINESS PARTNERS*/
export const GET_PROVIDERS_SUCCESS = 'GET_PROVIDERS_SUCCESS';
export const GET_PROVIDERS_FAIL = 'GET_PROVIDERS_FAIL';

export const GET_CONTACTS_SUCCESS = 'GET_CONTACTS_SUCCESS';
export const GET_CONTACTS_FAIL = 'GET_CONTACTS_FAIL';
export const ADD_CONTACT_SUCCESS = 'ADD_CONTACT_SUCCESS';
export const ADD_CONTACT_FAIL = 'ADD_CONTACT_FAIL';
export const UPDATE_CONTACT_SUCCESS = 'UPDATE_CONTACT_SUCCESS';
export const UPDATE_CONTACT_FAIL = 'UPDATE_CONTACT_FAIL';
export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS';
export const DELETE_CONTACT_FAIL = 'DELETE_CONTACT_FAIL';

export const GET_CLIENTS_SUCCESS = 'GET_CLIENTS_SUCCESS'
export const GET_CLIENTS_FAIL = 'GET_CLIENTS_FAIL'
export const DETAIL_CLIENT_SUCCESS = 'DETAIL_CLIENT_SUCCESS'
export const DETAIL_CLIENT_FAIL = 'DETAIL_CLIENT_FAIL'
export const DETAIL_PROVIDER_SUCCESS = 'DETAIL_PROVIDER_SUCCESS';
export const DETAIL_PROVIDER_FAIL = 'DETAIL_PROVIDER_FAIL';

export const GET_PROVIDERS_SALES_SUCCESS = 'GET_PROVIDERS_SALES_SUCCESS';
export const GET_PROVIDERS_SALES_FAIL = 'GET_PROVIDERS_SALES_FAIL';


/*AUTHENTICATION*/
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'
export const GET_USERS_FAIL = 'GET_USERS_FAIL'
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS'
export const ADD_USER_FAIL = 'ADD_USER_FAIL'
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS'
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_LOADED_FAIL = 'USER_LOADED_FAIL';
export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';
export const REMOVE_AUTH_LOADING = 'REMOVE_AUTH_LOADING';
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL';
export const REFRESH_SUCCESS = 'REFRESH_SUCCESS';
export const REFRESH_FAIL = 'REFRESH_FAIL';
export const LOGOUT = 'LOGOUT';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';


//RAW MATERIAL
export const GET_LOTS_SUCCESS = 'GET_LOTS_SUCCESS'
export const GET_LOTS_FAIL = 'GET_LOTS_FAIL'
export const ADD_LOT_SUCCESS = 'ADD_LOT_SUCCESS'
export const ADD_LOT_FAIL = 'ADD_LOT_FAIL'
export const GET_LOT_SUCCESS = 'GET_LOT_SUCCESS'
export const GET_LOT_FAIL = 'GET_LOT_FAIL'
export const DELETE_LOT_SUCCESS = 'DELETE_LOT_SUCCESS'
export const DELETE_LOT_FAIL = 'DELETE_LOT_FAIL'
export const GET_I_LOT_SUCCESS = 'GET_I_LOT_SUCCESS'
export const GET_I_LOT_FAIL = 'GET_I_LOT_FAIL'

export const ADD_I_LOT_SUCCESS = 'ADD_I_LOT_SUCCESS'
export const ADD_I_LOT_FAIL = 'ADD_I_LOT_FAIL'
export const UPDATE_I_LOT_SUCCESS = 'UPDATE_I_LOT_SUCCESS'
export const UPDATE_I_LOT_FAIL = 'UPDATE_I_LOT_FAIL'
export const DELETE_I_LOT_SUCCESS = 'DELETE_I_LOT_SUCCESS'
export const DELETE_I_LOT_FAIL = 'DELETE_I_LOT_FAIL'

