// Alerts
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';


/*Products*/
export const GET_FRUITS_SUCCESS = 'GET_FRUITS_SUCCESS';
export const GET_FRUITS_FAIL = 'GET_FRUITS_FAIL';

export const GET_PALLETS_SUCCESS = 'GET_PALLETS_SUCCESS';
export const GET_PALLETS_FAIL = 'GET_PALLETS_FAIL';

export const GET_BOXES_SUCCESS = 'GET_BOXES_SUCCESS';
export const GET_BOXES_FAIL = 'GET_BOXES_FAIL';

export const GET_BAGS_SUCCESS = 'GET_BAGS_SUCCESS';
export const GET_BAGS_FAIL = 'GET_BAGS_FAIL';

/*MANAGEMENT*/
export const GET_LOCATIONS_SUCCESS = 'GET_LOCATIONS_SUCCESS';
export const GET_LOCATIONS_FAIL = 'GET_LOCATIONS_FAIL';
export const GET_DATA_LOCATION_SUCCESS = 'GET_DATA_LOCATION_SUCCESS';
export const GET_DATA_LOCATION_FAIL = 'GET_DATA_LOCATION_FAIL';

export const GET_KARDEX_SUCCESS = 'GET_KARDEX_SUCCESS';
export const GET_KARDEX_FAIL = 'GET_KARDEX_FAIL';
export const ADD_KARDEX_SUCCESS = 'ADD_KARDEX_SUCCESS';
export const ADD_KARDEX_FAIL = 'ADD_KARDEX_FAIL';


export const GET_MOTIONS_SUCCESS = 'GET_MOTIONS_SUCCESS';
export const GET_MOTIONS_FAIL = 'GET_MOTIONS_FAIL';
export const DELETE_MOTION_SUCCESS = 'DELETE_MOTION_SUCCESS';
export const DELETE_MOTION_FAIL = 'DELETE_MOTION_FAIL';
export const ADD_MOTION_SUCCESS = 'ADD_MOTION_SUCCESS';
export const ADD_MOTION_FAIL = 'ADD_MOTION_FAIL';

export const GET_PAYMENTS_SUCCESS = 'GET_PAYMENTS_SUCCESS'
export const GET_PAYMENTS_FAIL = 'GET_PAYMENTS_FAIL'
export const ADD_PAYMENTS_SUCCESS = 'ADD_PAYMENTS_SUCCESS'
export const ADD_PAYMENTS_FAIL = 'ADD_PAYMENTS_FAIL'
export const UPDATE_PAYMENTS_SUCCESS = 'UPDATE_PAYMENTS_SUCCESS'
export const UPDATE_PAYMENTS_FAIL = 'UPDATE_PAYMENTS_FAIL'
export const DELETE_PAYMENTS_SUCCESS = 'DELETE_PAYMENTS_SUCCESS'
export const DELETE_PAYMENTS_FAIL = 'DELETE_PAYMENTS_FAIL'


/*BUSINESS PARTNERS*/
export const GET_PROVIDERS_SUCCESS = 'GET_PROVIDERS_SUCCESS';
export const GET_PROVIDERS_FAIL = 'GET_PROVIDERS_FAIL';

export const GET_CONTACTS_SUCCESS = 'GET_CONTACTS_SUCCESS';
export const GET_CONTACTS_FAIL = 'GET_CONTACTS_FAIL';
export const ADD_CONTACT_SUCCESS = 'ADD_CONTACT_SUCCESS';
export const ADD_CONTACT_FAIL = 'ADD_CONTACT_FAIL';
export const UPDATE_CONTACT_SUCCESS = 'UPDATE_CONTACT_SUCCESS';
export const UPDATE_CONTACT_FAIL = 'UPDATE_CONTACT_FAIL';
export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS';
export const DELETE_CONTACT_FAIL = 'DELETE_CONTACT_FAIL';

export const GET_CARRIER_SUCCESS = 'GET_CARRIER_SUCCESS';
export const GET_CARRIER_FAIL = 'GET_CARRIER_FAIL';
export const ADD_CARRIER_SUCCESS = 'ADD_CARRIER_SUCCESS';
export const ADD_CARRIER_FAIL = 'ADD_CARRIER_FAIL';
export const UPDATE_CARRIER_SUCCESS = 'UPDATE_CARRIER_SUCCESS';
export const UPDATE_CARRIER_FAIL = 'UPDATE_CARRIER_FAIL';
export const DELETE_CARRIER_SUCCESS = 'DELETE_CARRIER_SUCCESS';
export const DELETE_CARRIER_FAIL = 'DELETE_CARRIER_FAIL';

export const GET_CLIENTS_SUCCESS = 'GET_CLIENTS_SUCCESS'
export const GET_CLIENTS_FAIL = 'GET_CLIENTS_FAIL'
export const DETAIL_CLIENT_SUCCESS = 'DETAIL_CLIENT_SUCCESS'
export const DETAIL_CLIENT_FAIL = 'DETAIL_CLIENT_FAIL'
export const DETAIL_PROVIDER_SUCCESS = 'DETAIL_PROVIDER_SUCCESS';
export const DETAIL_PROVIDER_FAIL = 'DETAIL_PROVIDER_FAIL';

export const GET_PROVIDERS_SALES_SUCCESS = 'GET_PROVIDERS_SALES_SUCCESS';
export const GET_PROVIDERS_SALES_FAIL = 'GET_PROVIDERS_SALES_FAIL';
export const GET_CLIENTS_SALES_SUCCESS = 'GET_CLIENTS_SALES_SUCCESS';
export const GET_CLIENTS_SALES_FAIL = 'GET_CLIENTS_SALES_FAIL';

/*AUTHENTICATION*/
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'
export const GET_USERS_FAIL = 'GET_USERS_FAIL'
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS'
export const ADD_USER_FAIL = 'ADD_USER_FAIL'
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS'
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_LOADED_FAIL = 'USER_LOADED_FAIL';
export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';
export const REMOVE_AUTH_LOADING = 'REMOVE_AUTH_LOADING';
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL';
export const REFRESH_SUCCESS = 'REFRESH_SUCCESS';
export const REFRESH_FAIL = 'REFRESH_FAIL';
export const LOGOUT = 'LOGOUT';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';


//RAW MATERIAL
export const GET_LOTS_PRODUCTION_SUCCESS = 'GET_LOTS_PRODUCTION_SUCCESS';
export const GET_LOTS_PRODUCTION_FAIL = 'GET_LOTS_PRODUCTION_FAIL';
export const GET_LOTS_SUCCESS = 'GET_LOTS_SUCCESS'
export const GET_LOTS_FAIL = 'GET_LOTS_FAIL'
export const ADD_LOT_SUCCESS = 'ADD_LOT_SUCCESS'
export const ADD_LOT_FAIL = 'ADD_LOT_FAIL'
export const GET_LOT_SUCCESS = 'GET_LOT_SUCCESS'
export const GET_LOT_FAIL = 'GET_LOT_FAIL'
export const DELETE_LOT_SUCCESS = 'DELETE_LOT_SUCCESS'
export const DELETE_LOT_FAIL = 'DELETE_LOT_FAIL'
export const GET_I_LOT_SUCCESS = 'GET_I_LOT_SUCCESS'
export const GET_I_LOT_FAIL = 'GET_I_LOT_FAIL'

export const ADD_I_LOT_SUCCESS = 'ADD_I_LOT_SUCCESS'
export const ADD_I_LOT_FAIL = 'ADD_I_LOT_FAIL'
export const UPDATE_I_LOT_SUCCESS = 'UPDATE_I_LOT_SUCCESS'
export const UPDATE_I_LOT_FAIL = 'UPDATE_I_LOT_FAIL'
export const DELETE_I_LOT_SUCCESS = 'DELETE_I_LOT_SUCCESS'
export const DELETE_I_LOT_FAIL = 'DELETE_I_LOT_FAIL'


//QUALITY
export const GET_ANALYSIS_PINEAPPLE_SUCCESS = 'GET_ANALYSIS_PINEAPPLE_SUCCESS';
export const GET_ANALYSIS_PINEAPPLE_FAIL = 'GET_ANALYSIS_PINEAPPLE_FAIL';
export const UPDATE_ANALYSIS_PINEAPPLE_SUCCESS = 'UPDATE_ANALYSIS_PINEAPPLE_SUCCESS';
export const UPDATE_ANALYSIS_PINEAPPLE_FAIL = 'UPDATE_ANALYSIS_PINEAPPLE_FAIL';

export const GET_ANALYSIS_BANANO_SUCCESS = 'GET_ANALYSIS_BANANO_SUCCESS';
export const GET_ANALYSIS_BANANO_FAIL = 'GET_ANALYSIS_BANANO_FAIL';
export const UPDATE_ANALYSIS_BANANO_SUCCESS = 'UPDATE_ANALYSIS_BANANO_SUCCESS';
export const UPDATE_ANALYSIS_BANANO_FAIL = 'UPDATE_ANALYSIS_BANANO_FAIL';

export const GET_ANALYSIS_MANGO_SUCCESS = 'GET_ANALYSIS_MANGO_SUCCESS';
export const GET_ANALYSIS_MANGO_FAIL = 'GET_ANALYSIS_MANGO_FAIL';
export const UPDATE_ANALYSIS_MANGO_SUCCESS = 'UPDATE_ANALYSIS_MANGO_SUCCESS';
export const UPDATE_ANALYSIS_MANGO_FAIL = 'UPDATE_ANALYSIS_MANGO_FAIL';

export const GET_ANALYSIS_AGUAYMANTO_SUCCESS = 'GET_ANALYSIS_AGUAYMANTO_SUCCESS';
export const GET_ANALYSIS_AGUAYMANTO_FAIL = 'GET_ANALYSIS_AGUAYMANTO_FAIL';
export const UPDATE_ANALYSIS_AGUAYMANTO_SUCCESS = 'UPDATE_ANALYSIS_AGUAYMANTO_SUCCESS';
export const UPDATE_ANALYSIS_AGUAYMANTO_FAIL = 'UPDATE_ANALYSIS_AGUAYMANTO_FAIL';

export const GET_ANALYSIS_BLUEBERRY_SUCCESS = 'GET_ANALYSIS_BLUEBERRY_SUCCESS';
export const GET_ANALYSIS_BLUEBERRY_FAIL = 'GET_ANALYSIS_BLUEBERRY_FAIL';
export const UPDATE_ANALYSIS_BLUEBERRY_SUCCESS = 'UPDATE_ANALYSIS_BLUEBERRY_SUCCESS';
export const UPDATE_ANALYSIS_BLUEBERRY_FAIL = 'UPDATE_ANALYSIS_BLUEBERRY_FAIL';

export const GET_CUT_TEST_SUCCESS = 'GET_CUT_TEST_SUCCESS';
export const GET_CUT_TEST_FAIL = 'GET_CUT_TEST_FAIL';
export const UPDATE_CUT_TEST_SUCCESS = 'UPDATE_CUT_TEST_SUCCESS';
export const UPDATE_CUT_TEST_FAIL = 'UPDATE_CUT_TEST_FAIL';


//PROCESS LINE
export const GET_PROCESS_CONDITIONING_SUCCESS = 'GET_PROCESS_CONDITIONING_SUCCESS';
export const GET_PROCESS_CONDITIONING_FAIL = 'GET_PROCESS_CONDITIONING_FAIL';
export const GET_PROCESS_TERMINATED_SUCCESS = 'GET_PROCESS_TERMINATED_SUCCESS';
export const GET_PROCESS_TERMINATED_FAIL = 'GET_PROCESS_TERMINATED_FAIL';
export const GET_PROCESS_RELEASED_SUCCESS = 'GET_PROCESS_RELEASED_SUCCESS';
export const GET_PROCESS_RELEASED_FAIL = 'GET_PROCESS_RELEASED_FAIL';


export const GET_PROCESS_GENERAL_CONDITIONING_SUCCESS = 'GET_PROCESS_GENERAL_CONDITIONING_SUCCESS';
export const GET_PROCESS_GENERAL_CONDITIONING_FAIL = 'GET_PROCESS_GENERAL_CONDITIONING_FAIL';
export const GET_PROCESS_GENERAL_TERMINATED_SUCCESS = 'GET_PROCESS_GENERAL_TERMINATED_SUCCESS';
export const GET_PROCESS_GENERAL_TERMINATED_FAIL = 'GET_PROCESS_GENERAL_TERMINATED_FAIL';
export const GET_PROCESS_GENERAL_RELEASED_SUCCESS = 'GET_PROCESS_GENERAL_RELEASED_SUCCESS';
export const GET_PROCESS_GENERAL_RELEASED_FAIL = 'GET_PROCESS_GENERAL_RELEASED_FAIL';


export const DELETE_PROCESS_CONDITIONING_SUCCESS = 'DELETE_PROCESS_CONDITIONING_SUCCESS';
export const DELETE_PROCESS_CONDITIONING_FAIL = 'DELETE_PROCESS_CONDITIONING_FAIL';
export const DELETE_PROCESS_TERMINATED_SUCCESS = 'DELETE_PROCESS_TERMINATED_SUCCESS';
export const DELETE_PROCESS_TERMINATED_FAIL = 'DELETE_PROCESS_TERMINATED_FAIL';
export const DELETE_PROCESS_RELEASED_SUCCESS = 'DELETE_PROCESS_RELEASED_SUCCESS';
export const DELETE_PROCESS_RELEASED_FAIL = 'DELETE_PROCESS_RELEASED_FAIL';

export const ADD_PROCESS_CONDITIONING_SUCCESS = 'ADD_PROCESS_CONDITIONING_SUCCESS';
export const ADD_PROCESS_CONDITIONING_FAIL = 'ADD_PROCESS_CONDITIONING_FAIL';
export const ADD_PROCESS_TERMINATED_SUCCESS = 'ADD_PROCESS_TERMINATED_SUCCESS';
export const ADD_PROCESS_TERMINATED_FAIL = 'ADD_PROCESS_TERMINATED_FAIL';
export const ADD_PROCESS_RELEASED_SUCCESS = 'ADD_PROCESS_RELEASED_SUCCESS';
export const ADD_PROCESS_RELEASED_FAIL = 'ADD_PROCESS_RELEASED_FAIL';

export const UPDATE_PROCESS_CONDITIONING_SUCCESS = 'UPDATE_PROCESS_CONDITIONING_SUCCESS';
export const UPDATE_PROCESS_CONDITIONING_FAIL = 'UPDATE_PROCESS_CONDITIONING_FAIL';
export const UPDATE_PROCESS_TERMINATED_SUCCESS = 'UPDATE_PROCESS_TERMINATED_SUCCESS';
export const UPDATE_PROCESS_TERMINATED_FAIL = 'UPDATE_PROCESS_TERMINATED_FAIL';
export const UPDATE_PROCESS_RELEASED_SUCCESS = 'UPDATE_PROCESS_RELEASED_SUCCESS';
export const UPDATE_PROCESS_RELEASED_FAIL = 'UPDATE_PROCESS_RELEASED_FAIL';

export const GET_CUTS_SUCCESS = 'GET_CUTS_SUCCESS';
export const GET_CUTS_FAIL = 'GET_CUTS_FAIL';

export const GET_RECEPTION_RELEASED_SUCCESS = 'GET_RECEPTION_RELEASED_SUCCESS';
export const GET_RECEPTION_RELEASED_FAIL = 'GET_RECEPTION_RELEASED_FAIL';


//Warehouse
export const GET_PROGRAMS_SUCCESS = 'GET_PROGRAMS_SUCCESS';
export const GET_PROGRAMS_FAIL = 'GET_PROGRAMS_FAIL';
export const GET_PROGRAM_SUCCESS = 'GET_PROGRAM_SUCCESS';
export const GET_PROGRAM_FAIL = 'GET_PROGRAM_FAIL';
export const ADD_PROGRAM_SUCCESS = 'ADD_PROGRAM_SUCCESS';
export const ADD_PROGRAM_FAIL = 'ADD_PROGRAM_FAIL';
export const ADD_DATA_PROGRAM_SUCCESS = 'ADD_DATA_PROGRAM_SUCCESS';
export const ADD_DATA_PROGRAM_FAIL = 'ADD_DATA_PROGRAM_FAIL';
export const GET_DATA_PROGRAM_SUCCESS = 'GET_DATA_PROGRAM_SUCCESS';
export const GET_DATA_PROGRAM_FAIL = 'GET_DATA_PROGRAM_FAIL';
export const DELETE_DATA_PROGRAM_SUCCESS = 'DELETE_DATA_PROGRAM_SUCCESS';
export const DELETE_DATA_PROGRAM_FAIL = 'DELETE_DATA_PROGRAM_FAIL';
export const GET_PACKING_LIST_SUCCESS = 'GET_PACKING_LIST_SUCCESS';
export const GET_PACKING_LIST_FAIL = 'GET_PACKING_LIST_FAIL';
export const UPDATE_PACKING_LIST_SUCCESS = 'UPDATE_PACKING_LIST_SUCCESS';
export const UPDATE_PACKING_LIST_FAIL = 'UPDATE_PACKING_LIST_FAIL';
export const GET_PACKING_LIST_BY_SLUG_SUCCESS = 'GET_PACKING_LIST_BY_SLUG_SUCCESS';
export const GET_PACKING_LIST_BY_SLUG_FAIL = 'GET_PACKING_LIST_BY_SLUG_FAIL';
export const GET_LOTS_BY_SLUG_SUCCESS = 'GET_LOTS_BY_SLUG_SUCCESS';
export const GET_LOTS_BY_SLUG_FAIL = 'GET_LOTS_BY_SLUG_FAIL';
export const ADD_DATA_PACKING_LIST_SUCCESS = 'ADD_DATA_PACKING_LIST_SUCCESS';
export const ADD_DATA_PACKING_LIST_FAIL = 'ADD_DATA_PACKING_LIST_FAIL';
export const DELETE_DATA_PACKING_LIST_SUCCESS = 'DELETE_DATA_PACKING_LIST_SUCCESS';
export const DELETE_DATA_PACKING_LIST_FAIL = 'DELETE_DATA_PACKING_LIST_FAIL';

export const GET_DATA_PACKING_LIST_SUCCESS = 'GET_DATA_PACKING_LIST_SUCCESS';
export const GET_DATA_PACKING_LIST_FAIL = 'GET_DATA_PACKING_LIST_FAIL';


//PRODUCTION
export const GET_REPORT_PRODUCTION_SUCCESS = 'GET_REPORT_PRODUCTION_SUCCESS'
export const GET_REPORT_PRODUCTION_FAIL = 'GET_REPORT_PRODUCTION_FAIL'
export const GET_PRODUCTION_PINEAPPLE_SUCCESS = 'GET_PRODUCTION_PINEAPPLE_SUCCESS';
export const GET_PRODUCTION_PINEAPPLE_FAIL = 'GET_PRODUCTION_PINEAPPLE_FAIL';
export const ADD_PRODUCTION_PINEAPPLE_SUCCESS = 'ADD_PRODUCTION_PINEAPPLE_SUCCESS';
export const ADD_PRODUCTION_PINEAPPLE_FAIL = 'ADD_PRODUCTION_PINEAPPLE_FAIL';
export const UPDATE_PRODUCTION_PINEAPPLE_SUCCESS = 'UPDATE_PRODUCTION_PINEAPPLE_SUCCESS';
export const UPDATE_PRODUCTION_PINEAPPLE_FAIL = 'UPDATE_PRODUCTION_PINEAPPLE_FAIL';
export const DELETE_PRODUCTION_PINEAPPLE_SUCCESS = 'DELETE_PRODUCTION_PINEAPPLE_SUCCESS';
export const DELETE_PRODUCTION_PINEAPPLE_FAIL = 'DELETE_PRODUCTION_PINEAPPLE_FAIL';

export const DETAIL_PRODUCTION_PINEAPPLE_SUCCESS = 'DETAIL_PRODUCTION_PINEAPPLE_SUCCESS';
export const DETAIL_PRODUCTION_PINEAPPLE_FAIL = 'DETAIL_PRODUCTION_PINEAPPLE_FAIL';

export const ADD_CROWN_PINEAPPLE_SUCCESS = 'ADD_CROWN_PINEAPPLE_SUCCESS';
export const ADD_CROWN_PINEAPPLE_FAIL = 'ADD_CROWN_PINEAPPLE_FAIL';
export const DELETE_CROWN_PINEAPPLE_SUCCESS = 'DELETE_CROWN_PINEAPPLE_SUCCESS';
export const DELETE_CROWN_PINEAPPLE_FAIL = 'DELETE_CROWN_PINEAPPLE_FAIL';

export const ADD_PEEL_PINEAPPLE_SUCCESS = 'ADD_PEEL_PINEAPPLE_SUCCESS';
export const ADD_PEEL_PINEAPPLE_FAIL = 'ADD_PEEL_PINEAPPLE_FAIL';
export const DELETE_PEEL_PINEAPPLE_SUCCESS = 'DELETE_PEEL_PINEAPPLE_SUCCESS';
export const DELETE_PEEL_PINEAPPLE_FAIL = 'DELETE_PEEL_PINEAPPLE_FAIL';


// REPORT
export const GET_REPORT_SUCCESS = 'GET_REPORT_SUCCESS';
export const GET_REPORT_FAIL = 'GET_REPORT_FAIL';
export const GET_PROVIDERS_CATEGORY_SUCCESS = 'GET_PROVIDERS_CATEGORY_SUCCESS';
export const GET_PROVIDERS_CATEGORY_FAIL = 'GET_PROVIDERS_CATEGORY_FAIL';
export const GET_SUMMARY_CATEGORY_SUCCESS = 'GET_SUMMARY_CATEGORY_SUCCESS';
export const GET_SUMMARY_CATEGORY_FAIL = 'GET_SUMMARY_CATEGORY_FAIL';

export const UPDATE_REPORT_SUCCESS = 'UPDATE_REPORT_SUCCESS';
export const UPDATE_REPORT_FAIL = 'UPDATE_REPORT_FAIL';


//Commercial
export const GET_PRODUCTS_COMMERCIAL_SUCCESS = 'GET_PRODUCTS_COMMERCIAL_SUCCESS';
export const GET_PRODUCTS_COMMERCIAL_FAIL = 'GET_PRODUCTS_COMMERCIAL_FAIL';


export const GET_FAMILY_COMMERCIAL_SUCCESS = 'GET_FAMILY_COMMERCIAL_SUCCESS';
export const GET_FAMILY_COMMERCIAL_FAIL = 'GET_FAMILY_COMMERCIAL_FAIL';

export const GET_GROUP_COMMERCIAL_SUCCESS = 'GET_GROUP_COMMERCIAL_SUCCESS';
export const GET_GROUP_COMMERCIAL_FAIL = 'GET_GROUP_COMMERCIAL_FAIL';

export const GET_TYPE_COMMERCIAL_SUCCESS = 'GET_TYPE_COMMERCIAL_SUCCESS';
export const GET_TYPE_COMMERCIAL_FAIL = 'GET_TYPE_COMMERCIAL_FAIL';

export const GET_CUT_COMMERCIAL_SUCCESS = 'GET_CUT_COMMERCIAL_SUCCESS';
export const GET_CUT_COMMERCIAL_FAIL = 'GET_CUT_COMMERCIAL_FAIL';

export const GET_VARIETY_COMMERCIAL_SUCCESS = 'GET_VARIETY_COMMERCIAL_SUCCESS';
export const GET_VARIETY_COMMERCIAL_FAIL = 'GET_VARIETY_COMMERCIAL_FAIL';

export const GET_CLIENT_COMMERCIAL_SUCCESS = 'GET_CLIENT_COMMERCIAL_SUCCESS';
export const GET_CLIENT_COMMERCIAL_FAIL = 'GET_CLIENT_COMMERCIAL_FAIL';

export const GET_PRESENTATION_COMMERCIAL_SUCCESS = 'GET_PRESENTATION_COMMERCIAL_SUCCESS';
export const GET_PRESENTATION_COMMERCIAL_FAIL = 'GET_PRESENTATION_COMMERCIAL_FAIL';

export const GET_PACKAGING_COMMERCIAL_SUCCESS = 'GET_PACKAGING_COMMERCIAL_SUCCESS';
export const GET_PACKAGING_COMMERCIAL_FAIL = 'GET_PACKAGING_COMMERCIAL_FAIL';

export const GET_PACKING_COMMERCIAL_SUCCESS = 'GET_PACKING_COMMERCIAL_SUCCESS';
export const GET_PACKING_COMMERCIAL_FAIL = 'GET_PACKING_COMMERCIAL_FAIL';

export const GET_PROVIDER_COMMERCIAL_SUCCESS = 'GET_PROVIDER_COMMERCIAL_SUCCESS';
export const GET_PROVIDER_COMMERCIAL_FAIL = 'GET_PROVIDER_COMMERCIAL_FAIL';

export const GET_CONDITION_COMMERCIAL_SUCCESS = 'GET_CONDITION_COMMERCIAL_SUCCESS';
export const GET_CONDITION_COMMERCIAL_FAIL = 'GET_CONDITION_COMMERCIAL_FAIL';

export const GET_LOTS_COMMERCIAL_SUCCESS = 'GET_LOTS_COMMERCIAL_SUCCESS';
export const GET_LOTS_COMMERCIAL_FAIL = 'GET_LOTS_COMMERCIAL_FAIL';

export const ADD_LOT_COMMERCIAL_SUCCESS = 'ADD_LOT_COMMERCIAL_SUCCESS';
export const ADD_LOT_COMMERCIAL_FAIL = 'ADD_LOT_COMMERCIAL_FAIL';


