# Generated by Django 3.2 on 2022-11-18 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('raw_material', '0003_rename_informacion_ilot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_camp', models.DecimalField(blank=True, decimal_places=9, default=0, max_digits=12, null=True, verbose_name='Precio Campo')),
                ('freight', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=12, null=True, verbose_name='Flete')),
                ('observations', models.CharField(blank=True, max_length=100, null=True, verbose_name='Observaciones')),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=12, null=True)),
                ('type', models.CharField(choices=[('campo', 'campo'), ('planta', 'planta')], default='plant', max_length=10, verbose_name='Referencia de Precio')),
                ('type_kg', models.CharField(choices=[('guia', 'guia'), ('neto', 'neto')], default='net', max_length=10, verbose_name='Referencia de kg aprovechables')),
                ('type_discount', models.CharField(choices=[('guia', 'guia'), ('neto', 'neto')], default='net', max_length=10, verbose_name='Referencia de kg a descontar')),
                ('lot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='raw_material.lot', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
                'ordering': ['-id'],
            },
        ),
    ]
