# Generated by Django 3.2 on 2022-11-28 12:00

from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('raw_material', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalReport',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('price_camp', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Precio Campo')),
                ('freight', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=9, null=True, verbose_name='Flete')),
                ('observations', models.CharField(blank=True, max_length=100, null=True, verbose_name='Observaciones')),
                ('type', models.CharField(choices=[('campo', 'campo'), ('planta', 'planta')], default='planta', max_length=10, verbose_name='Referencia de Precio')),
                ('type_kg', models.CharField(choices=[('guia', 'guia'), ('neto', 'neto'), ('bruto', 'bruto')], default='neto', max_length=10, verbose_name='Referencia de kg aprovechables')),
                ('type_discount', models.CharField(choices=[('guia', 'guia'), ('neto', 'neto'), ('bruto', 'bruto')], default='neto', max_length=10, verbose_name='Referencia de kg a descontar')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Registro',
                'verbose_name_plural': 'historical Registros',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_camp', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Precio Campo')),
                ('freight', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=9, null=True, verbose_name='Flete')),
                ('observations', models.CharField(blank=True, max_length=100, null=True, verbose_name='Observaciones')),
                ('type', models.CharField(choices=[('campo', 'campo'), ('planta', 'planta')], default='planta', max_length=10, verbose_name='Referencia de Precio')),
                ('type_kg', models.CharField(choices=[('guia', 'guia'), ('neto', 'neto'), ('bruto', 'bruto')], default='neto', max_length=10, verbose_name='Referencia de kg aprovechables')),
                ('type_discount', models.CharField(choices=[('guia', 'guia'), ('neto', 'neto'), ('bruto', 'bruto')], default='neto', max_length=10, verbose_name='Referencia de kg a descontar')),
                ('lot', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='report', to='raw_material.lot', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
                'ordering': ['-id'],
            },
        ),
    ]
