# Generated by Django 3.2 on 2022-11-17 21:18

import apps.raw_material.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0005_auto_20221117_2110'),
        ('business_partners', '0003_auto_20221117_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=100, verbose_name='Origen')),
                ('parcel', models.CharField(blank=True, default='No Parcel', max_length=100, null=True, verbose_name='Parcela')),
                ('carrierGuide', models.CharField(max_length=12, verbose_name='Guia de transporte')),
                ('providerGuide', models.CharField(max_length=12, verbose_name='Guia de proveedor')),
                ('docs', models.FileField(blank=True, null=True, upload_to=apps.raw_material.models.custom_doc_file_path, verbose_name='Documentos')),
                ('entryDate', models.DateField(verbose_name='Fecha de entrada')),
                ('starting_point_date', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio de partida')),
                ('downloadDate', models.DateField(verbose_name='Fecha de descarga')),
                ('weight_guide', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=11, null=True, verbose_name='Peso Guia')),
                ('condition', models.CharField(blank=True, max_length=100, null=True, verbose_name='Condición')),
                ('variety', models.CharField(blank=True, max_length=100, null=True, verbose_name='Variedad')),
                ('departure_time', models.TimeField(blank=True, null=True, verbose_name='Hora de Salida de Acopio')),
                ('arrival_time', models.TimeField(blank=True, null=True, verbose_name='Hora de Llegada a Planta')),
                ('lot', models.CharField(max_length=13, unique=True, verbose_name='Lote')),
                ('quality', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3, null=True, verbose_name='Muestra de Calidad')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripcion')),
                ('certified', models.CharField(blank=True, max_length=500, null=True, verbose_name='Certificado')),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=8, null=True, verbose_name='Porcentaje de Descuento')),
                ('closed', models.BooleanField(default=False, verbose_name='Cerrado/Abierto')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fruit_entry', to='products.fruits', verbose_name='Categoria')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_entry', to='business_partners.providermp', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Lote de Materia Prima',
                'verbose_name_plural': 'Lotes de Materia Prima',
                'ordering': ['-downloadDate'],
            },
        ),
    ]
