# Generated by Django 3.2 on 2022-11-28 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0003_initial'),
        ('products', '0002_initial'),
        ('raw_material', '0001_initial'),
        ('business_partners', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallot',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicallot',
            name='provider',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='business_partners.providermp', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='historicalilot',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalilot',
            name='location',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='management.location', verbose_name='Ubicacion'),
        ),
        migrations.AddField(
            model_name='historicalilot',
            name='lot',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='raw_material.lot', verbose_name='Lote'),
        ),
        migrations.AddField(
            model_name='historicalilot',
            name='pallet',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.pallets', verbose_name='Pallet'),
        ),
    ]
