# Generated by Django 3.2 on 2022-11-17 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20221117_2110'),
        ('raw_material', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lot',
            options={'ordering': ['-downloadDate'], 'verbose_name': 'Lote', 'verbose_name_plural': 'Lotes'},
        ),
        migrations.CreateModel(
            name='Informacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Numero de pallet')),
                ('weight', models.FloatField(default=0, verbose_name='Peso bruto')),
                ('final_weight', models.FloatField(default=0, verbose_name='Peso final')),
                ('gb', models.IntegerField(default=0, verbose_name='GreenBox')),
                ('pa', models.IntegerField(default=0, verbose_name='PAE')),
                ('co', models.IntegerField(default=0, verbose_name='Colores')),
                ('t0', models.IntegerField(default=0, verbose_name='Tibana 0')),
                ('t1', models.IntegerField(default=0, verbose_name='Tibana 1')),
                ('t2', models.IntegerField(default=0, verbose_name='Tibana 2')),
                ('gn', models.IntegerField(default=0, verbose_name='Gandules')),
                ('ma', models.IntegerField(default=0, verbose_name='Madera')),
                ('tare', models.FloatField(default=0, verbose_name='Tara')),
                ('c6', models.IntegerField(default=0, verbose_name='Calibre 6')),
                ('c8', models.IntegerField(default=0, verbose_name='Calibre 8')),
                ('c10', models.IntegerField(default=0, verbose_name='Calibre 10')),
                ('c12', models.IntegerField(default=0, verbose_name='Calibre 12')),
                ('c14', models.IntegerField(default=0, verbose_name='Calibre 14')),
                ('dateIndicted', models.DateField(blank=True, null=True, verbose_name='Fecha de procesado')),
                ('indicted', models.BooleanField(default=False, verbose_name='Procesado')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='raw_material.lot', verbose_name='Lote')),
                ('pallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pallet', to='products.pallets', verbose_name='Pallet')),
            ],
            options={
                'verbose_name': 'Informacion de Lotes',
                'verbose_name_plural': 'Informacion de Lotes',
                'ordering': ['number'],
            },
        ),
    ]
