# Generated by Django 3.2 on 2022-11-17 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20221117_2110'),
        ('raw_material', '0002_auto_20221117_2159'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Informacion',
            new_name='ILot',
        ),
    ]
