# Generated by Django 3.2 on 2022-11-30 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_partners', '0004_businessmaquila_historicalbusinessmaquila'),
        ('raw_material', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallot',
            name='maquila',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='business_partners.businessmaquila'),
        ),
        migrations.AddField(
            model_name='lot',
            name='maquila',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business_partners.businessmaquila'),
        ),
    ]
