# Generated by Django 3.2 on 2022-11-17 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_partners', '0003_auto_20221117_2110'),
        ('process_line', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotPT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot', models.CharField(max_length=50)),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('stock', models.PositiveSmallIntegerField(default=0)),
                ('expirationDate', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('container', models.CharField(blank=True, default=' ', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lote',
                'ordering': ['-id'],
                'unique_together': {('lot', 'container')},
            },
        ),
        migrations.CreateModel(
            name='PackingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='Estado')),
                ('order', models.CharField(blank=True, default=' ', max_length=6, verbose_name='Orden')),
                ('quantity', models.PositiveSmallIntegerField(default=0, verbose_name='Bolsas')),
                ('weight_bags', models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='Peso')),
            ],
            options={
                'verbose_name': 'Packing List',
                'verbose_name_plural': 'Packing List',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('PEPS', 'PEPS'), ('UEPS', 'UEPS')], default='PEPS', max_length=4, verbose_name='Método')),
                ('type', models.CharField(choices=[('FCL', 'FCL'), ('LCL', 'LCL')], default='FCL', max_length=3, verbose_name='Tipo')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Número')),
                ('denomination', models.CharField(blank=True, default=' ', max_length=50, verbose_name='Denominación')),
                ('client', models.ManyToManyField(related_name='receptions', to='business_partners.Client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Programa de recepción',
                'verbose_name_plural': 'Programas de recepción',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ReceptionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha de recepción')),
                ('packing', models.BooleanField(default=False, verbose_name='Conformidad - Envasado')),
                ('quality', models.BooleanField(default=False, verbose_name='Conformidad - Calidad')),
                ('logistic', models.BooleanField(default=False, verbose_name='Conformidad - Logística')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptions', to='process_line.processlinereleased')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reception_details', to='warehouse.reception', verbose_name='Programa')),
            ],
            options={
                'verbose_name': 'Datos de recepción',
                'verbose_name_plural': 'Datos de recepción',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PackingListInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(default=0, verbose_name='Número')),
                ('boxes', models.PositiveSmallIntegerField(default=0, verbose_name='Cantidad')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_list_information', to='warehouse.lotpt', verbose_name='Lote')),
                ('packing_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_list_information', to='warehouse.packinglist', verbose_name='Packing List')),
            ],
            options={
                'verbose_name': 'Información de Packing List',
                'verbose_name_plural': 'Información de Packing List',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='packinglist',
            name='reception',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='packing_list', to='warehouse.reception', verbose_name='Recepción'),
        ),
    ]
