# Generated by Django 3.2 on 2022-11-17 20:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderMP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('business_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razón Social')),
                ('ruc', models.CharField(blank=True, max_length=15, null=True, verbose_name='RUC')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ciudad')),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='País')),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Postal')),
                ('contact', models.CharField(blank=True, max_length=255, null=True, verbose_name='Contacto')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cargo')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Correo Electrónico')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('payment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Forma de Pago')),
                ('money', models.CharField(choices=[('1', 'USD'), ('2', 'EUR'), ('3', 'SOLES')], default='1', max_length=1, verbose_name='Moneda')),
                ('image', models.URLField(blank=True, max_length=255, null=True, verbose_name='Imagen')),
                ('slug', models.SlugField(blank=True, default=uuid.uuid1, max_length=255, null=True, verbose_name='Slug')),
                ('code', models.CharField(blank=True, max_length=2, null=True, unique=True, verbose_name='Código')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock')),
            ],
            options={
                'verbose_name': 'Proveedor Materia Prima',
                'verbose_name_plural': 'Proveedores Materia Prima',
                'ordering': ['name'],
            },
        ),
    ]
