# Generated by Django 3.2 on 2022-11-17 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_partners', '0002_client_providerpacking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('ruc', models.CharField(blank=True, max_length=11, null=True, verbose_name='RUC')),
                ('code', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Placa')),
            ],
            options={
                'verbose_name': 'Empresa de Transporte',
                'verbose_name_plural': 'Empresas de Transporte',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('dni', models.IntegerField(blank=True, null=True, verbose_name='DNI')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Correo Electrónico')),
                ('phone', models.IntegerField(verbose_name='Teléfono')),
                ('licence', models.CharField(blank=True, max_length=9, null=True, verbose_name='Licencia')),
                ('reference', models.CharField(blank=True, max_length=50, null=True, verbose_name='Referencia')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-id'], 'verbose_name': 'Cliente Comercial', 'verbose_name_plural': 'Clientes Comerciales'},
        ),
    ]
