# Generated by Django 3.2 on 2022-11-30 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business_partners', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessMaquila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('business_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razón Social')),
                ('ruc', models.CharField(blank=True, max_length=15, null=True, verbose_name='RUC')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ciudad')),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='País')),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Postal')),
                ('contact', models.CharField(blank=True, max_length=255, null=True, verbose_name='Contacto')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cargo')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Correo Electrónico')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('payment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Forma de Pago')),
                ('money', models.CharField(choices=[('1', 'USD'), ('2', 'EUR'), ('3', 'SOLES')], default='1', max_length=1, verbose_name='Moneda')),
                ('image', models.URLField(blank=True, max_length=255, null=True, verbose_name='Imagen')),
                ('slug', models.SlugField(blank=True, default=uuid.uuid1, max_length=255, null=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Empresa de Maquila',
                'verbose_name_plural': 'Empresas de Maquila',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalBusinessMaquila',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('business_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razón Social')),
                ('ruc', models.CharField(blank=True, max_length=15, null=True, verbose_name='RUC')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ciudad')),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='País')),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Postal')),
                ('contact', models.CharField(blank=True, max_length=255, null=True, verbose_name='Contacto')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cargo')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Correo Electrónico')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('payment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Forma de Pago')),
                ('money', models.CharField(choices=[('1', 'USD'), ('2', 'EUR'), ('3', 'SOLES')], default='1', max_length=1, verbose_name='Moneda')),
                ('image', models.URLField(blank=True, max_length=255, null=True, verbose_name='Imagen')),
                ('slug', models.SlugField(blank=True, default=uuid.uuid1, max_length=255, null=True, verbose_name='Slug')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Empresa de Maquila',
                'verbose_name_plural': 'historical Empresas de Maquila',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
