# Generated by Django 3.2 on 2022-11-17 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('raw_material', '0003_rename_informacion_ilot'),
    ]

    operations = [
        migrations.CreateModel(
            name='CutTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caliber', models.CharField(choices=[('6', '6'), ('8', '8'), ('10', '10'), ('12', '12'), ('14', '14')], default='6', max_length=2, verbose_name='Calibre')),
                ('cut_fresh_1_8', models.IntegerField(blank=True, default=0, null=True, verbose_name='Peso en fresco (corte 1/8)')),
                ('cut_1_8', models.IntegerField(blank=True, default=0, null=True, verbose_name='Peso corte <> 1/8')),
                ('eyes', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Ojitos')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cut_test', to='raw_material.lot', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Prueba de Corte para Piña',
                'verbose_name_plural': 'Prueba de Corte para Piña',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisPineapple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maturation_0_plant', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Maduración 0 Planta %')),
                ('maturation_1_plant', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Maduración 1 Planta %')),
                ('maturation_2_plant', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Maduración 2 Planta %')),
                ('maturation_3_plant', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Maduración 3 Planta %')),
                ('maturation_4_plant', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Maduración 4 Planta %')),
                ('maturation_5_plant', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Maduración 5 Planta %')),
                ('lot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_pineapple', to='raw_material.lot', verbose_name='Lote MP')),
            ],
            options={
                'verbose_name': 'Análisis de Piña',
                'verbose_name_plural': 'Análisis de Piña',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisMango',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_1_5', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Color <1-5')),
                ('color_1_5_2', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Color 1,5 -  2')),
                ('color_3', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Color >=3')),
                ('brix_7_9', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Brix 7-9')),
                ('brix_10_12', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Brix 10-12')),
                ('brix_13', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Brix >13')),
                ('weight_280', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Peso <280 ')),
                ('weight_280_300', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Peso 280-300 ')),
                ('weight_300', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Peso >300 ')),
                ('cracked_mechanical_damage', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Rajados y daños mecanicos')),
                ('sun_damage', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Daños de sol')),
                ('anthracnose', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Antracnosis')),
                ('rot', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Pudricion')),
                ('soft', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Blando')),
                ('advanced', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Avanzado')),
                ('insect_bite', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Picadura de insectos')),
                ('unharmed', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Sin daños')),
                ('lot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_mango', to='raw_material.lot', verbose_name='Lote MP')),
            ],
            options={
                'verbose_name': 'Análisis de Mango',
                'verbose_name_plural': 'Análisis de Mango',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisBlueberry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_brix', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Brix promedio')),
                ('max_brix', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Brix máximo')),
                ('min_brix', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Brix mínimo')),
                ('caliber_1', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Calibre 1 <=11')),
                ('caliber_2', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Calibre 2 12 -18')),
                ('caliber_3', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Calibre 3 >=19')),
                ('green', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Verde')),
                ('crushed', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Aplastado')),
                ('mechanical_damages', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Daños mecánicos')),
                ('unharmed', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Sin daños')),
                ('lot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_blueberry', to='raw_material.lot', verbose_name='Lote MP')),
            ],
            options={
                'verbose_name': 'Análisis de Arándanos',
                'verbose_name_plural': 'Análisis de Arándanos',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisBanano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maturation_1', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Maduración 1 %')),
                ('maturation_2', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Maduración 2 %')),
                ('mechanical_damages', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Daños mecánicos')),
                ('broken_neck', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Corte de cuello')),
                ('chafing', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Rozadura')),
                ('scar', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Cicatriz')),
                ('unharmed', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Sin daños')),
                ('lot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_banano', to='raw_material.lot', verbose_name='Lote MP')),
            ],
            options={
                'verbose_name': 'Análisis de Banano',
                'verbose_name_plural': 'Análisis de Banano',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisAguaymanto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maturation_1', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Maduración 1 %')),
                ('maturation_2', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Maduración 2 %')),
                ('maturation_3', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Maduración 3 %')),
                ('mushroom', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Hongos y fermentado')),
                ('green', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Verde')),
                ('cracked', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Rajado')),
                ('crushed', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Aplastado')),
                ('phytosanitary', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Fitosanitario')),
                ('watery', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Consistencia aguada')),
                ('defects', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Defectos')),
                ('lot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_aguaymanto', to='raw_material.lot', verbose_name='Lote MP')),
            ],
            options={
                'verbose_name': 'Análisis de Aguaymanto',
                'verbose_name_plural': 'Análisis de Aguaymanto',
                'ordering': ['-id'],
            },
        ),
    ]
