# Generated by Django 3.2 on 2022-12-04 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisaguaymanto',
            name='defects',
        ),
        migrations.RemoveField(
            model_name='analysisblueberry',
            name='unharmed',
        ),
        migrations.RemoveField(
            model_name='analysismango',
            name='color_1_5_2_5',
        ),
        migrations.RemoveField(
            model_name='historicalanalysisaguaymanto',
            name='defects',
        ),
        migrations.RemoveField(
            model_name='historicalanalysisblueberry',
            name='unharmed',
        ),
        migrations.RemoveField(
            model_name='historicalanalysismango',
            name='color_1_5_2_5',
        ),
        migrations.AddField(
            model_name='analysismango',
            name='color_1_5',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Color 1,5 '),
        ),
        migrations.AddField(
            model_name='analysismango',
            name='color_2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Color 2'),
        ),
        migrations.AddField(
            model_name='analysismango',
            name='color_2_5',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Color 2,5'),
        ),
        migrations.AddField(
            model_name='historicalanalysismango',
            name='color_1_5',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Color 1,5 '),
        ),
        migrations.AddField(
            model_name='historicalanalysismango',
            name='color_2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Color 2'),
        ),
        migrations.AddField(
            model_name='historicalanalysismango',
            name='color_2_5',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Color 2,5'),
        ),
        migrations.AlterField(
            model_name='analysismango',
            name='color_3',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Color 3'),
        ),
        migrations.AlterField(
            model_name='historicalanalysismango',
            name='color_3',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Color 3'),
        ),
    ]
