# Generated by Django 3.2 on 2022-11-17 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_partners', '0003_auto_20221117_2110'),
        ('products', '0005_auto_20221117_2110'),
        ('raw_material', '0003_rename_informacion_ilot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre')),
                ('business_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Razón social')),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Peso neto')),
                ('receipt', models.CharField(blank=True, max_length=12, null=True, verbose_name='Recibo')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto total')),
                ('status', models.BooleanField(default=False, verbose_name='Estado')),
                ('cancelled', models.DateField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entry_report', to='raw_material.lot', verbose_name='Reporte')),
            ],
            options={
                'verbose_name': 'Pagos y Recibos',
                'verbose_name_plural': 'Pagos y Recibos',
                'ordering': ['-receipt'],
            },
        ),
        migrations.CreateModel(
            name='Motion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Cantidad')),
                ('fr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fr', to='business_partners.providermp', verbose_name='Destino')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to', to='business_partners.providermp', verbose_name='Origen')),
            ],
            options={
                'verbose_name': 'Movimiento de Jaba',
                'verbose_name_plural': 'Movimientos de Jaba',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Kardex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('input', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Entrada')),
                ('output', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Salida')),
                ('stock', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Stock')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kardex_category', to='products.fruits', verbose_name='Fruta')),
            ],
            options={
                'verbose_name': 'Registros',
                'verbose_name_plural': 'Registro',
                'ordering': ['-date'],
                'unique_together': {('date', 'category')},
            },
        ),
    ]
