# Generated by Django 3.2 on 2022-11-28 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
        ('raw_material', '0001_initial'),
        ('business_partners', '0002_providermp_category'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='entry_report', to='raw_material.lot', verbose_name='Reporte'),
        ),
        migrations.AddField(
            model_name='motion',
            name='fr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fr', to='business_partners.providermp', verbose_name='Destino'),
        ),
        migrations.AddField(
            model_name='motion',
            name='to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to', to='business_partners.providermp', verbose_name='Origen'),
        ),
        migrations.AddField(
            model_name='kardex',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kardex_category', to='products.fruits', verbose_name='Fruta'),
        ),
    ]
