# Generated by Django 3.2 on 2022-11-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lot',
            options={'ordering': ['name', 'production_date'], 'verbose_name': 'Lotes', 'verbose_name_plural': 'Lotes'},
        ),
        migrations.AddField(
            model_name='product',
            name='from_color',
            field=models.CharField(blank=True, max_length=50, verbose_name='From color'),
        ),
        migrations.AddField(
            model_name='product',
            name='to',
            field=models.CharField(blank=True, max_length=50, verbose_name='To color'),
        ),
        migrations.AddField(
            model_name='product',
            name='via',
            field=models.CharField(blank=True, max_length=50, verbose_name='Vía color'),
        ),
    ]
