# Generated by Django 3.2 on 2022-11-30 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0002_auto_20221130_1003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lot',
            old_name='type',
            new_name='type_inf',
        ),
    ]
