# Generated by Django 3.2 on 2022-11-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0003_rename_type_lot_type_inf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='fcl',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='FCL'),
        ),
    ]
