# Generated by Django 3.2 on 2022-11-28 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('raw_material', '0001_initial'),
        ('process_line', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processlineconditioning',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conditioning', to='raw_material.lot', verbose_name='Lote Materia Prima'),
        ),
    ]
