# Generated by Django 3.2 on 2022-11-17 23:31

import apps.comex.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Programa de despacho')),
                ('destine', models.CharField(max_length=50, verbose_name='Destino')),
                ('guide', models.CharField(max_length=50, verbose_name='Guía de remisión')),
                ('order', models.CharField(max_length=50, verbose_name='Orden de Pedido')),
                ('docs', models.FileField(upload_to=apps.comex.models.custom_doc_file_path, verbose_name='Documentación')),
            ],
            options={
                'verbose_name': 'COMEX',
                'verbose_name_plural': 'COMEX',
                'ordering': ['-date'],
            },
        ),
    ]
