# Generated by Django 3.2 on 2022-11-17 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comex', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentation',
            name='packing_list',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documentation', to='warehouse.packinglist'),
        ),
    ]
