# Generated by Django 3.2 on 2022-11-17 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comex', '0002_documentation_packing_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentation',
            options={'ordering': ['-date'], 'verbose_name': 'Documentación', 'verbose_name_plural': 'Documentación'},
        ),
    ]
